// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.daozhang.py

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object NativeRuntimeApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class LinuxLikeRuntimeInfo (
  val available: Boolean,
  val installed: Boolean,
  val message: String,
  val pythonPath: String,
  val pipPath: String,
  val rootfsDir: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): LinuxLikeRuntimeInfo {
      val available = pigeonVar_list[0] as Boolean
      val installed = pigeonVar_list[1] as Boolean
      val message = pigeonVar_list[2] as String
      val pythonPath = pigeonVar_list[3] as String
      val pipPath = pigeonVar_list[4] as String
      val rootfsDir = pigeonVar_list[5] as String
      return LinuxLikeRuntimeInfo(available, installed, message, pythonPath, pipPath, rootfsDir)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      available,
      installed,
      message,
      pythonPath,
      pipPath,
      rootfsDir,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as LinuxLikeRuntimeInfo
    return NativeRuntimeApiPigeonUtils.deepEquals(this.available, other.available) && NativeRuntimeApiPigeonUtils.deepEquals(this.installed, other.installed) && NativeRuntimeApiPigeonUtils.deepEquals(this.message, other.message) && NativeRuntimeApiPigeonUtils.deepEquals(this.pythonPath, other.pythonPath) && NativeRuntimeApiPigeonUtils.deepEquals(this.pipPath, other.pipPath) && NativeRuntimeApiPigeonUtils.deepEquals(this.rootfsDir, other.rootfsDir)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.available)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.installed)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.message)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.pythonPath)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.pipPath)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.rootfsDir)
    return result
  }
  override fun toString(): String {
    return "LinuxLikeRuntimeInfo(available=$available, installed=$installed, message=$message, pythonPath=$pythonPath, pipPath=$pipPath, rootfsDir=$rootfsDir)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAppFileEntry (
  val path: String,
  val name: String,
  val isDirectory: Boolean,
  val size: Long,
  val modifiedAtMillis: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAppFileEntry {
      val path = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val isDirectory = pigeonVar_list[2] as Boolean
      val size = pigeonVar_list[3] as Long
      val modifiedAtMillis = pigeonVar_list[4] as Long
      return NativeAppFileEntry(path, name, isDirectory, size, modifiedAtMillis)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      name,
      isDirectory,
      size,
      modifiedAtMillis,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAppFileEntry
    return NativeRuntimeApiPigeonUtils.deepEquals(this.path, other.path) && NativeRuntimeApiPigeonUtils.deepEquals(this.name, other.name) && NativeRuntimeApiPigeonUtils.deepEquals(this.isDirectory, other.isDirectory) && NativeRuntimeApiPigeonUtils.deepEquals(this.size, other.size) && NativeRuntimeApiPigeonUtils.deepEquals(this.modifiedAtMillis, other.modifiedAtMillis)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.path)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.name)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.isDirectory)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.size)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.modifiedAtMillis)
    return result
  }
  override fun toString(): String {
    return "NativeAppFileEntry(path=$path, name=$name, isDirectory=$isDirectory, size=$size, modifiedAtMillis=$modifiedAtMillis)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativePythonInfo (
  val pythonVersion: String,
  val sitePackages: String,
  val pythonPath: String,
  val chaquopyPipDir: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativePythonInfo {
      val pythonVersion = pigeonVar_list[0] as String
      val sitePackages = pigeonVar_list[1] as String
      val pythonPath = pigeonVar_list[2] as String
      val chaquopyPipDir = pigeonVar_list[3] as String
      return NativePythonInfo(pythonVersion, sitePackages, pythonPath, chaquopyPipDir)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      pythonVersion,
      sitePackages,
      pythonPath,
      chaquopyPipDir,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativePythonInfo
    return NativeRuntimeApiPigeonUtils.deepEquals(this.pythonVersion, other.pythonVersion) && NativeRuntimeApiPigeonUtils.deepEquals(this.sitePackages, other.sitePackages) && NativeRuntimeApiPigeonUtils.deepEquals(this.pythonPath, other.pythonPath) && NativeRuntimeApiPigeonUtils.deepEquals(this.chaquopyPipDir, other.chaquopyPipDir)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.pythonVersion)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.sitePackages)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.pythonPath)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.chaquopyPipDir)
    return result
  }
  override fun toString(): String {
    return "NativePythonInfo(pythonVersion=$pythonVersion, sitePackages=$sitePackages, pythonPath=$pythonPath, chaquopyPipDir=$chaquopyPipDir)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeAppInfo (
  val appName: String,
  val packageName: String,
  val version: String,
  val buildNumber: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeAppInfo {
      val appName = pigeonVar_list[0] as String
      val packageName = pigeonVar_list[1] as String
      val version = pigeonVar_list[2] as String
      val buildNumber = pigeonVar_list[3] as String
      return NativeAppInfo(appName, packageName, version, buildNumber)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appName,
      packageName,
      version,
      buildNumber,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeAppInfo
    return NativeRuntimeApiPigeonUtils.deepEquals(this.appName, other.appName) && NativeRuntimeApiPigeonUtils.deepEquals(this.packageName, other.packageName) && NativeRuntimeApiPigeonUtils.deepEquals(this.version, other.version) && NativeRuntimeApiPigeonUtils.deepEquals(this.buildNumber, other.buildNumber)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.appName)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.packageName)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.version)
    result = 31 * result + NativeRuntimeApiPigeonUtils.deepHash(this.buildNumber)
    return result
  }
  override fun toString(): String {
    return "NativeAppInfo(appName=$appName, packageName=$packageName, version=$version, buildNumber=$buildNumber)"
  }
}
private open class NativeRuntimeApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          LinuxLikeRuntimeInfo.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAppFileEntry.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativePythonInfo.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeAppInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is LinuxLikeRuntimeInfo -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is NativeAppFileEntry -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is NativePythonInfo -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is NativeAppInfo -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface RuntimeHostApi {
  fun getLinuxLikeRuntimeInfo(): LinuxLikeRuntimeInfo
  fun getPythonInfo(callback: (Result<NativePythonInfo>) -> Unit)

  companion object {
    /** The codec used by RuntimeHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeRuntimeApiPigeonCodec()
    }
    /** Sets up an instance of `RuntimeHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: RuntimeHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.RuntimeHostApi.getLinuxLikeRuntimeInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getLinuxLikeRuntimeInfo())
            } catch (exception: Throwable) {
              NativeRuntimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.RuntimeHostApi.getPythonInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getPythonInfo{ result: Result<NativePythonInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(NativeRuntimeApiPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(NativeRuntimeApiPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FilePickerHostApi {
  fun getFilePickerRoots(): List<NativeAppFileEntry>
  fun listFilePickerDirectory(path: String): List<NativeAppFileEntry>
  fun readFilePickerFile(path: String): ByteArray

  companion object {
    /** The codec used by FilePickerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeRuntimeApiPigeonCodec()
    }
    /** Sets up an instance of `FilePickerHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FilePickerHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.FilePickerHostApi.getFilePickerRoots$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getFilePickerRoots())
            } catch (exception: Throwable) {
              NativeRuntimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.FilePickerHostApi.listFilePickerDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.listFilePickerDirectory(pathArg))
            } catch (exception: Throwable) {
              NativeRuntimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.FilePickerHostApi.readFilePickerFile$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.readFilePickerFile(pathArg))
            } catch (exception: Throwable) {
              NativeRuntimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface AppHostApi {
  fun getAppInfo(): NativeAppInfo
  fun checkOverlayPermission(): Boolean
  fun consumePendingRunScript(): String?

  companion object {
    /** The codec used by AppHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      NativeRuntimeApiPigeonCodec()
    }
    /** Sets up an instance of `AppHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: AppHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.AppHostApi.getAppInfo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getAppInfo())
            } catch (exception: Throwable) {
              NativeRuntimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.AppHostApi.checkOverlayPermission$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.checkOverlayPermission())
            } catch (exception: Throwable) {
              NativeRuntimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.python_runner.AppHostApi.consumePendingRunScript$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.consumePendingRunScript())
            } catch (exception: Throwable) {
              NativeRuntimeApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
