buildscript {
    def androidAgpVersion = providers.gradleProperty("androidAgpVersion").get()
    def kotlinGradlePluginVersion = providers.gradleProperty("kotlinGradlePluginVersion").get()

    repositories {
        if (System.getenv("CI") != "true") {
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/central" }
            maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        }
        google()
        mavenCentral()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:${androidAgpVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:${kotlinGradlePluginVersion}"
        classpath "com.chaquo.python:gradle:17.0.0"
    }
}

allprojects {
    repositories {
        if (System.getenv("CI") != "true") {
            maven { url "https://maven.aliyun.com/repository/google" }
            maven { url "https://maven.aliyun.com/repository/central" }
        }
        google()
        mavenCentral()
    }
}

subprojects {
    def androidAgpVersion = providers.gradleProperty("androidAgpVersion").get()
    def kotlinGradlePluginVersion = providers.gradleProperty("kotlinGradlePluginVersion").get()

    buildscript {
        repositories {
            if (System.getenv("CI") != "true") {
                maven { url "https://maven.aliyun.com/repository/google" }
                maven { url "https://maven.aliyun.com/repository/central" }
                maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
            }
            google()
            mavenCentral()
        }
        configurations.matching { it.name == "classpath" }.configureEach {
            resolutionStrategy.eachDependency { details ->
                if (details.requested.group == "com.android.tools.build" &&
                    details.requested.name == "gradle") {
                    details.useVersion(androidAgpVersion)
                }
                if (details.requested.group == "org.jetbrains.kotlin" &&
                    details.requested.name == "kotlin-gradle-plugin") {
                    details.useVersion(kotlinGradlePluginVersion)
                }
            }
        }
    }
}

def newBuildDir = rootProject.layout.buildDirectory.dir("../../build").get()
rootProject.layout.buildDirectory.value(newBuildDir)

subprojects {
    def newSubprojectBuildDir = newBuildDir.dir(project.name)
    project.layout.buildDirectory.value(newSubprojectBuildDir)
}

tasks.register("clean", Delete) {
    delete rootProject.layout.buildDirectory
}
