// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class LinuxLikeRuntimeInfo {
  LinuxLikeRuntimeInfo({
    required this.available,
    required this.installed,
    required this.message,
    required this.pythonPath,
    required this.pipPath,
    required this.rootfsDir,
  });

  bool available;

  bool installed;

  String message;

  String pythonPath;

  String pipPath;

  String rootfsDir;

  List<Object?> _toList() {
    return <Object?>[
      available,
      installed,
      message,
      pythonPath,
      pipPath,
      rootfsDir,
    ];
  }

  Object encode() {
    return _toList();  }

  static LinuxLikeRuntimeInfo decode(Object result) {
    result as List<Object?>;
    return LinuxLikeRuntimeInfo(
      available: result[0]! as bool,
      installed: result[1]! as bool,
      message: result[2]! as String,
      pythonPath: result[3]! as String,
      pipPath: result[4]! as String,
      rootfsDir: result[5]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LinuxLikeRuntimeInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(available, other.available) && _deepEquals(installed, other.installed) && _deepEquals(message, other.message) && _deepEquals(pythonPath, other.pythonPath) && _deepEquals(pipPath, other.pipPath) && _deepEquals(rootfsDir, other.rootfsDir);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'LinuxLikeRuntimeInfo(available: $available, installed: $installed, message: $message, pythonPath: $pythonPath, pipPath: $pipPath, rootfsDir: $rootfsDir)';
  }
}

class NativeAppFileEntry {
  NativeAppFileEntry({
    required this.path,
    required this.name,
    required this.isDirectory,
    required this.size,
    required this.modifiedAtMillis,
  });

  String path;

  String name;

  bool isDirectory;

  int size;

  int modifiedAtMillis;

  List<Object?> _toList() {
    return <Object?>[
      path,
      name,
      isDirectory,
      size,
      modifiedAtMillis,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAppFileEntry decode(Object result) {
    result as List<Object?>;
    return NativeAppFileEntry(
      path: result[0]! as String,
      name: result[1]! as String,
      isDirectory: result[2]! as bool,
      size: result[3]! as int,
      modifiedAtMillis: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAppFileEntry || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) && _deepEquals(name, other.name) && _deepEquals(isDirectory, other.isDirectory) && _deepEquals(size, other.size) && _deepEquals(modifiedAtMillis, other.modifiedAtMillis);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAppFileEntry(path: $path, name: $name, isDirectory: $isDirectory, size: $size, modifiedAtMillis: $modifiedAtMillis)';
  }
}

class NativePythonInfo {
  NativePythonInfo({
    required this.pythonVersion,
    required this.sitePackages,
    required this.pythonPath,
    required this.chaquopyPipDir,
  });

  String pythonVersion;

  String sitePackages;

  String pythonPath;

  String chaquopyPipDir;

  List<Object?> _toList() {
    return <Object?>[
      pythonVersion,
      sitePackages,
      pythonPath,
      chaquopyPipDir,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativePythonInfo decode(Object result) {
    result as List<Object?>;
    return NativePythonInfo(
      pythonVersion: result[0]! as String,
      sitePackages: result[1]! as String,
      pythonPath: result[2]! as String,
      chaquopyPipDir: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePythonInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(pythonVersion, other.pythonVersion) && _deepEquals(sitePackages, other.sitePackages) && _deepEquals(pythonPath, other.pythonPath) && _deepEquals(chaquopyPipDir, other.chaquopyPipDir);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePythonInfo(pythonVersion: $pythonVersion, sitePackages: $sitePackages, pythonPath: $pythonPath, chaquopyPipDir: $chaquopyPipDir)';
  }
}

class NativeAppInfo {
  NativeAppInfo({
    required this.appName,
    required this.packageName,
    required this.version,
    required this.buildNumber,
  });

  String appName;

  String packageName;

  String version;

  String buildNumber;

  List<Object?> _toList() {
    return <Object?>[
      appName,
      packageName,
      version,
      buildNumber,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeAppInfo decode(Object result) {
    result as List<Object?>;
    return NativeAppInfo(
      appName: result[0]! as String,
      packageName: result[1]! as String,
      version: result[2]! as String,
      buildNumber: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeAppInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(appName, other.appName) && _deepEquals(packageName, other.packageName) && _deepEquals(version, other.version) && _deepEquals(buildNumber, other.buildNumber);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeAppInfo(appName: $appName, packageName: $packageName, version: $version, buildNumber: $buildNumber)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is LinuxLikeRuntimeInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAppFileEntry) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is NativePythonInfo) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is NativeAppInfo) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return LinuxLikeRuntimeInfo.decode(readValue(buffer)!);
      case 130:
        return NativeAppFileEntry.decode(readValue(buffer)!);
      case 131:
        return NativePythonInfo.decode(readValue(buffer)!);
      case 132:
        return NativeAppInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class RuntimeHostApi {
  /// Constructor for [RuntimeHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  RuntimeHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<LinuxLikeRuntimeInfo> getLinuxLikeRuntimeInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.RuntimeHostApi.getLinuxLikeRuntimeInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as LinuxLikeRuntimeInfo;
  }

  Future<NativePythonInfo> getPythonInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.RuntimeHostApi.getPythonInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativePythonInfo;
  }
}

class FilePickerHostApi {
  /// Constructor for [FilePickerHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FilePickerHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<List<NativeAppFileEntry>> getFilePickerRoots() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.FilePickerHostApi.getFilePickerRoots$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeAppFileEntry>();
  }

  Future<List<NativeAppFileEntry>> listFilePickerDirectory(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.FilePickerHostApi.listFilePickerDirectory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<NativeAppFileEntry>();
  }

  Future<Uint8List> readFilePickerFile(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.FilePickerHostApi.readFilePickerFile$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as Uint8List;
  }
}

class AppHostApi {
  /// Constructor for [AppHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  AppHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeAppInfo> getAppInfo() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.AppHostApi.getAppInfo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeAppInfo;
  }

  Future<bool> checkOverlayPermission() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.AppHostApi.checkOverlayPermission$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as bool;
  }

  Future<String?> consumePendingRunScript() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.python_runner.AppHostApi.consumePendingRunScript$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
    return pigeonVar_replyValue as String?;
  }
}
